import type { Property } from '@/lib/types';
export const properties: Property[] = [
  { id: 'batroun-sunset', name: 'Batroun Sunset Coastal Retreat', region: 'Batroun', area: 'Batroun, North Lebanon', image: '/images/af75ed5b6b6a6f0d.jpg', price: 160, rating: 4.9, reviews: 128, guests: 6, bedrooms: 3, bathrooms: 2, amenities: ['24/7 Solar Power', 'Private Pool', 'Sea View'], status: 'Approved' },
  { id: 'cedars-summit', name: 'Cedars Summit Stone Lodge', region: 'Faraya', area: 'Faraya, Mount Lebanon', image: '/images/81723d32ab713d6e.jpg', price: 185, rating: 4.9, reviews: 94, guests: 8, bedrooms: 4, bathrooms: 3, amenities: ['24/7 Solar Power', 'Fireplace', 'Mountain View'], status: 'Approved' },
  { id: 'azure-coast', name: 'Azure Coast Beachfront Chalet', region: 'Sour', area: 'Sour, South Lebanon', image: '/images/1f566744ddc73f8d.jpg', price: 120, rating: 4.8, reviews: 86, guests: 4, bedrooms: 2, bathrooms: 2, amenities: ['24/7 Solar Power', 'Private Pool', 'Beach Access'], status: 'Approved' },
  { id: 'saida-heritage', name: 'Saida Heritage Garden Villa', region: 'Saida', area: 'Saida, South Lebanon', image: '/images/fc1018e8d13663f9.jpg', price: 95, rating: 4.7, reviews: 72, guests: 5, bedrooms: 2, bathrooms: 1, amenities: ['Fast Wi-Fi', 'Garden', 'Traditional House'], status: 'Approved' },
  { id: 'tyre-port', name: 'Tyre Port Traditional Villa', region: 'Sour', area: 'Tyre Old Port, Sour', image: '/images/dc0b315b162e2a76.jpg', price: 140, rating: 4.9, reviews: 45, guests: 6, bedrooms: 3, bathrooms: 2, amenities: ['24/7 Solar Power', 'Sea View', 'Fast Wi-Fi'], status: 'Approved' },
  { id: 'al-fanar', name: 'Al-Fanar Horizon Lodge', region: 'Sour', area: 'Al-Fanar, Sour', image: '/images/af75ed5b6b6a6f0d.jpg', price: 175, rating: 4.8, reviews: 38, guests: 4, bedrooms: 2, bathrooms: 2, amenities: ['Private Pool', 'Sea View', 'Fast Wi-Fi'], status: 'Approved' },
  { id: 'citrus-orchard', name: 'Sour Citrus Orchard Chalet', region: 'Sour', area: 'Abbasiyeh, Sour', image: '/images/fc1018e8d13663f9.jpg', price: 85, rating: 4.6, reviews: 29, guests: 5, bedrooms: 2, bathrooms: 1, amenities: ['Garden', 'BBQ Area', '24/7 Solar Power'], status: 'Approved' },
  { id: 'mediterranean-stone', name: 'Mediterranean Stone Retreat', region: 'Sour', area: 'Naqoura Coast, Sour', image: '/images/1f566744ddc73f8d.jpg', price: 210, rating: 4.9, reviews: 62, guests: 8, bedrooms: 4, bathrooms: 3, amenities: ['Private Pool', 'Beach Access', '24/7 Solar Power'], status: 'Approved' },
  { id: 'byblos-horizon', name: 'Byblos Horizon Bay Villa', region: 'Byblos', area: 'Amchit, Byblos', image: '/images/a17c09290530d2aa.jpg', price: 150, rating: 4.8, reviews: 41, guests: 6, bedrooms: 3, bathrooms: 2, amenities: ['Sea View', 'Fast Wi-Fi', 'Private Pool'], status: 'Approved' },
];
export const ownerProperties: Property[] = properties.slice(0, 6).map((property, index) => ({ ...property, status: index === 4 ? 'Pending' : index === 5 ? 'Action Required' : 'Approved' }));
