'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { SlidersHorizontal, Search, Heart, ArrowUpDown } from 'lucide-react';
import { properties } from '@/lib/mock-data/properties';
import { PropertyCard } from './PropertyCard';
import { useFeedback } from '@/components/ui/AppProvider';
import { useLocalState } from '@/lib/use-local-state';
export function PropertyBrowser({ mode = 'search', filters = false, initialRegion = '' }: { mode?: 'home' | 'search' | 'favorites'; filters?: boolean; initialRegion?: string }) {
  const [saved, setSaved] = useLocalState<string[]>('stayleb:favorites',properties.slice(0, 4).map(p => p.id));
  const [query, setQuery] = useState(''); const [region, setRegion] = useState(initialRegion); const [sort, setSort] = useState('recommended'); const [max, setMax] = useState(250); const [guests, setGuests] = useState(1); const [pool, setPool] = useState(false); const [page, setPage] = useState(1); const [showFilters, setShowFilters] = useState(filters); const { notify } = useFeedback();
  useEffect(() => { const params = new URLSearchParams(window.location.search); const q = params.get('q'); const r = params.get('region'); if(q || r) { queueMicrotask(() => { setQuery(q || ''); setRegion(r || ''); }); } }, []);
  function toggle(id: string) { const next = saved.includes(id) ? saved.filter(x => x !== id) : [...saved, id]; setSaved(next); localStorage.setItem('stayleb:favorites', JSON.stringify(next)); notify(next.includes(id) ? 'Property saved to favorites.' : 'Property removed from favorites.'); }
  const results = useMemo(() => { const list = properties.filter(p => (mode !== 'favorites' || saved.includes(p.id)) && (!query || `${p.name} ${p.area} ${p.amenities.join(' ')}`.toLowerCase().includes(query.toLowerCase())) && (!region || p.region === region) && p.price <= max && p.guests >= guests && (!pool || p.amenities.includes('Private Pool'))); if (sort === 'low') list.sort((a,b) => a.price-b.price); if (sort === 'high') list.sort((a,b) => b.price-a.price); if (sort === 'rating') list.sort((a,b) => b.rating-a.rating); return mode === 'home' ? list.slice(0,4) : list; }, [mode,saved,query,region,max,guests,pool,sort]);
  const pageSize = 6; const pages = Math.max(1, Math.ceil(results.length/pageSize)); const current = Math.min(page,pages); const visible = mode === 'home' ? results : results.slice((current-1)*pageSize,current*pageSize);
  return <section className="max-w-7xl mx-auto px-4 md:px-6 py-8 w-full">
    <div className="flex flex-wrap items-end justify-between gap-4 mb-6"><div>{mode === 'home' && <p className="text-[11px] tracking-widest uppercase text-primary mb-1">Verified coastal & mountain collections</p>}<h1 className={mode === 'home' ? 'text-2xl font-semibold' : 'text-3xl font-semibold'}>{mode === 'home' ? 'Recommended Approved Stays' : mode === 'favorites' ? 'Favorites' : `${results.length} Approved Stays${region ? ` in ${region}` : ' in Lebanon'}`}</h1><p className="text-sm text-on-surface-variant mt-1">{mode === 'favorites' ? 'Your collection of saved Lebanese retreats.' : 'Curated coastal escapes, mountain hideaways, and authentic Lebanese hospitality.'}</p></div>{mode === 'home' ? <Link href="/search" className="text-primary text-xs font-semibold">View all verified chalets →</Link> : <button className="button-secondary" onClick={() => setShowFilters(!showFilters)} aria-expanded={showFilters}><SlidersHorizontal size={16}/>Refine Results</button>}</div>
    {mode !== 'home' && <div className="flex flex-wrap items-center gap-3 mb-6"><label className="relative flex-1 min-w-48"><Search size={17} className="absolute left-3 top-3.5 text-outline"/><input aria-label="Search stays" placeholder="Search properties or destinations" className="form-input pl-10 w-full" value={query} onChange={e => { setQuery(e.target.value); setPage(1); }}/></label><label className="flex items-center gap-2 text-xs"><ArrowUpDown size={15}/><select aria-label="Sort properties" className="form-input" value={sort} onChange={e => setSort(e.target.value)}><option value="recommended">Recommended</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="rating">Highest rated</option></select></label></div>}
    <div className={`grid gap-6 ${showFilters && mode !== 'home' ? 'lg:grid-cols-[250px_1fr]' : ''}`}>
      {showFilters && mode !== 'home' && <aside className="bg-white rounded-2xl p-5 self-start space-y-6 shadow-sm"><div className="flex justify-between items-center"><h2 className="font-semibold">Filter Properties</h2><button className="text-xs text-primary underline" onClick={() => { setRegion('');setMax(250);setGuests(1);setPool(false);setQuery('');setPage(1); }}>Reset All</button></div><label className="block text-sm font-medium">Destination<select className="form-input w-full mt-2" value={region} onChange={e => {setRegion(e.target.value);setPage(1);}}><option value="">All Lebanon</option>{['Sour','Batroun','Faraya','Saida','Byblos'].map(r => <option key={r}>{r}</option>)}</select></label><label className="block text-sm font-medium">Nightly price: up to ${max}<input className="w-full mt-3" type="range" min={80} max={250} step={5} value={max} onChange={e => {setMax(Number(e.target.value));setPage(1);}}/></label><label className="block text-sm font-medium">Guests<input type="number" min={1} max={8} value={guests} className="form-input w-full mt-2" onChange={e => {setGuests(Number(e.target.value));setPage(1);}}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={pool} onChange={e => {setPool(e.target.checked);setPage(1);}}/>Private pool</label><p className="text-xs text-on-surface-variant">{results.length} stays match your filters.</p></aside>}
      <div>{visible.length ? <div className={`grid grid-cols-1 sm:grid-cols-2 ${mode === 'home' ? 'lg:grid-cols-4' : showFilters ? 'xl:grid-cols-2' : 'lg:grid-cols-3'} gap-5`}>{visible.map(p => <PropertyCard property={p} saved={saved.includes(p.id)} onSave={toggle} key={p.id}/>)}</div> : <div className="text-center py-16 bg-white rounded-2xl"><Heart className="mx-auto text-primary mb-4"/><h2 className="font-semibold text-xl">{mode === 'favorites' ? 'No saved chalets yet' : 'No matching stays'}</h2><p className="text-on-surface-variant mt-2">{mode === 'favorites' ? 'Save a property using its heart button to see it here.' : 'Try a different destination or broaden your filters.'}</p><Link href="/search" className="button-primary mt-5">Explore properties</Link></div>}
      {mode !== 'home' && results.length > pageSize && <nav aria-label="Property result pages" className="flex justify-center items-center gap-2 mt-8"><button className="button-secondary" disabled={current===1} onClick={() => setPage(current-1)}>Previous</button>{Array.from({length:pages},(_,i) => <button key={i} className={current===i+1?'button-primary':'button-secondary'} aria-current={current===i+1?'page':undefined} onClick={() => setPage(i+1)}>{i+1}</button>)}<button className="button-secondary" disabled={current===pages} onClick={() => setPage(current+1)}>Next</button></nav>}</div>
    </div>
  </section>;
}
