'use client';
import Link from 'next/link';
import { Heart, MapPin, Star, Users, BedDouble, Bath, Zap } from 'lucide-react';
import type { Property } from '@/lib/types';
export function PropertyCard({ property: p, saved, onSave }: { property: Property; saved: boolean; onSave: (id: string) => void }) {
  return <article className="property-card bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-lg transition-shadow">
    <div className="relative aspect-[16/10]"><Link href={`/properties/${p.id}`}><img src={p.image} alt={p.name} className="w-full h-full object-cover"/></Link><span className="absolute top-3 left-3 rounded-full bg-white/95 text-primary text-[10px] font-semibold px-2 py-1">✓ Verified Retreat</span><button type="button" aria-label={saved ? `Remove ${p.name} from favorites` : `Save ${p.name} to favorites`} aria-pressed={saved} onClick={() => onSave(p.id)} className="absolute top-3 right-3 rounded-full bg-white/95 p-2 text-primary shadow"><Heart size={17} fill={saved ? 'currentColor' : 'none'}/></button><span className="absolute left-3 bottom-3 rounded-full bg-white/90 px-2 py-1 text-[10px] text-primary flex items-center gap-1"><Zap size={12}/>24/7 Power</span></div>
    <div className="p-4"><div className="flex items-center justify-between gap-2 text-[10px] text-on-surface-variant"><span className="flex items-center gap-1"><MapPin size={11}/>{p.area}</span><span className="flex items-center gap-1 text-primary font-semibold"><Star size={11} fill="currentColor"/>{p.rating} <span className="text-outline font-normal">({p.reviews})</span></span></div><h3 className="font-semibold text-sm leading-5 my-2"><Link href={`/properties/${p.id}`}>{p.name}</Link></h3><div className="flex gap-3 text-[11px] text-on-surface-variant mb-3"><span className="flex gap-1 items-center"><Users size={12}/>{p.guests} guests</span><span className="flex gap-1 items-center"><BedDouble size={12}/>{p.bedrooms} beds</span><span className="flex gap-1 items-center"><Bath size={12}/>{p.bathrooms} baths</span></div><div className="flex flex-wrap gap-1 mb-4">{p.amenities.map(a => <span key={a} className="bg-surface-container-low rounded px-1.5 py-0.5 text-[9px] text-on-surface-variant">{a}</span>)}</div><div className="flex items-center justify-between pt-3 border-t border-outline-variant/20"><Link href={`/properties/${p.id}`} className="text-xs text-primary font-semibold">View stay →</Link><span className="text-primary font-bold text-lg">${p.price}<small className="font-normal text-[10px] text-outline"> /night</small></span></div></div>
  </article>;
}
