from fastapi import HTTPException, status
from google import genai
import json

from app.config import settings
from app.schemas.ai import (
    PropertyDescriptionGenerateRequest,
    AIPropertySearchFilters,
)
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.models.amenity import Amenity
from app.services.property_search_service import search_properties

def generate_property_description(
    data: PropertyDescriptionGenerateRequest,
) -> str:
    # -------------------------------------------------
    # Check Gemini configuration
    # -------------------------------------------------

    if not settings.gemini_api_key:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="AI service is not configured",
        )

    # -------------------------------------------------
    # Gemini client
    # -------------------------------------------------

    client = genai.Client(
        api_key=settings.gemini_api_key
    )

    # -------------------------------------------------
    # Amenities
    # -------------------------------------------------

    amenities_text = (
        ", ".join(data.amenities)
        if data.amenities
        else "None provided"
    )

    # -------------------------------------------------
    # Rules
    # -------------------------------------------------

    rules_lines = []

    for rule in data.rules:
        rule_text = (
            f"- {rule.name}: "
            f"{'Allowed' if rule.allowed else 'Not allowed'}"
        )

        if rule.value:
            rule_text += f" ({rule.value})"

        rules_lines.append(rule_text)

    rules_text = (
        "\n".join(rules_lines)
        if rules_lines
        else "None provided"
    )

    # Convert furnished_house -> furnished house
    property_type = data.property_type.replace(
        "_",
        " ",
    )

    # -------------------------------------------------
    # Gemini prompt
    # -------------------------------------------------

    prompt = f"""
You are writing a property listing description for StayLeb,
a chalet and furnished-house rental platform in Lebanon.

Write a professional, attractive, natural property description
using ONLY the information supplied below.

PROPERTY INFORMATION

Title: {data.title}
Property type: {property_type}
Location: {data.location}
Bedrooms: {data.bedrooms}
Beds: {data.beds}
Bathrooms: {data.bathrooms}
Maximum guests: {data.max_guests}

Amenities:
{amenities_text}

Property rules:
{rules_text}

IMPORTANT RULES

- Use only facts explicitly supplied above.
- Never invent amenities or property features.
- Never invent sea views, mountain views, scenery, balconies,
  gardens, pools, parking, Wi-Fi, air conditioning, heating,
  fireplaces, or other facilities unless supplied as amenities.
- Never invent nearby attractions, distances, landmarks,
  neighborhood characteristics, or travel times.
- Never invent ratings or reviews.
- Never invent pricing, discounts, or availability.
- Never claim the property is luxurious, peaceful, spacious,
  modern, newly renovated, or similar unless supported by the
  supplied information.
- Do not expose internal system information.
- Do not mention that this description was generated by AI.
- Do not include a heading such as "Property Description".
- Do not use bullet points.
- Do not use emojis.
- Do not repeat the property title unnecessarily.
- Keep the description concise and suitable for a rental listing.
- Write approximately 100 to 160 words.
- Mention useful amenities naturally when they are provided.
- Mention important property rules naturally only when useful.
- Do not make unsupported claims.

Return ONLY the final property description.
""".strip()

    # -------------------------------------------------
    # Generate description
    # -------------------------------------------------

    try:
        response = client.models.generate_content(
            model="gemini-3.5-flash",
            contents=prompt,
        )

        description = (
            response.text.strip()
            if response.text
            else ""
        )

        # Gemini responded but did not generate text
        if not description:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail="AI service returned an empty response",
            )

        return description

    # -------------------------------------------------
    # Preserve our own HTTP errors
    # -------------------------------------------------

    except HTTPException:
        raise

    # -------------------------------------------------
    # Gemini/provider failure
    # -------------------------------------------------

    except Exception as e:
        # Keep detailed provider errors in the backend console only.
        print(
            "GEMINI ERROR:",
            repr(e),
        )

        # Do not expose Gemini internals/API information to frontend.
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "StayLeb AI is temporarily unavailable. "
                "Please try again shortly."
            ),
        )

def extract_property_search_filters(
    query: str,
) -> AIPropertySearchFilters:
    """
    Convert a natural-language property search into structured filters.

    Gemini only interprets the user's request.
    It does NOT select or invent StayLeb properties.
    """

    if not settings.gemini_api_key:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="AI service is not configured",
        )

    client = genai.Client(
        api_key=settings.gemini_api_key
    )

    prompt = f"""
You convert natural-language property searches into structured
search filters for StayLeb, a chalet and furnished-house rental
platform in Lebanon.

USER SEARCH:
{query}

Extract only information explicitly stated or clearly requested
by the user.

Return ONLY valid JSON with exactly these fields:

{{
  "location": null,
  "guests": null,
  "min_price": null,
  "max_price": null,
  "property_type": null,
  "bedrooms": null,
  "bathrooms": null,
  "beds": null,
  "amenities": []
}}

RULES:

- location must be a location explicitly requested by the user.
- guests must be an integer or null.
- min_price and max_price must be numbers or null.
- property_type must be exactly:
  "chalet",
  "furnished_house",
  or null.
- If the user says "furnished house", use "furnished_house".
- bedrooms, bathrooms, and beds must be integers or null.
- amenities must contain only amenity names explicitly requested.
- Do not invent filters.
- Do not invent amenities.
- Do not infer requirements that the user did not request.
- Do not return property names or property IDs.
- Do not recommend properties.
- Do not include explanations.
- Do not include markdown.
- Do not wrap the JSON in code fences.
""".strip()

    try:
        response = client.models.generate_content(
            model="gemini-3.5-flash",
            contents=prompt,
        )

        if not response.text:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail="AI service returned an empty response",
            )

        raw_text = response.text.strip()

        # Defensive cleanup in case the model still
        # returns a fenced JSON block.
        if raw_text.startswith("```"):
            raw_text = raw_text.removeprefix("```json")
            raw_text = raw_text.removeprefix("```")
            raw_text = raw_text.removesuffix("```")
            raw_text = raw_text.strip()

        try:
            parsed = json.loads(raw_text)

        except json.JSONDecodeError:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail="AI service returned an invalid search response",
            )

        try:
            filters = AIPropertySearchFilters(
                **parsed
            )

        except Exception:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail="AI service returned invalid search filters",
            )

        return filters

    except HTTPException:
        raise

    except Exception as exc:
        print(
            "GEMINI AI SEARCH ERROR:",
            repr(exc),
        )

        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "StayLeb AI search is temporarily unavailable. "
                "Please try again shortly."
            ),
        )

def resolve_ai_amenity_ids(
    db: Session,
    amenity_names: list[str],
) -> list[int] | None:
    """
    Resolve AI-extracted amenity names against real,
    active StayLeb amenities.

    Returns:
    - [] when no amenities were requested
    - list[int] when every requested amenity was resolved
    - None when at least one requested amenity cannot be resolved
    """

    if not amenity_names:
        return []

    # ---------------------------------
    # Normalize requested names
    # ---------------------------------

    normalized_names = []

    for name in amenity_names:
        normalized = name.strip().lower()

        if (
            normalized
            and normalized not in normalized_names
        ):
            normalized_names.append(normalized)

    if not normalized_names:
        return []

    # ---------------------------------
    # Load real active StayLeb amenities
    # ---------------------------------

    active_amenities = (
        db.query(Amenity)
        .filter(
            Amenity.is_active.is_(True)
        )
        .all()
    )

    amenity_ids = []

    # ---------------------------------
    # Resolve each requested amenity
    # ---------------------------------

    for requested_name in normalized_names:

        matched_amenity = None

        # 1. Exact case-insensitive match
        for amenity in active_amenities:
            database_name = amenity.name.strip().lower()

            if database_name == requested_name:
                matched_amenity = amenity
                break

        # 2. Safe word/phrase containment
        #
        # Example:
        # "pool" matches "swimming pool"
        # "sea view" matches "sea view"
        #
        # We only accept the match when exactly
        # one active amenity matches, avoiding
        # ambiguous mappings.
        if matched_amenity is None:

            possible_matches = []

            for amenity in active_amenities:
                database_name = amenity.name.strip().lower()

                if (
                    requested_name in database_name
                    or database_name in requested_name
                ):
                    possible_matches.append(amenity)

            if len(possible_matches) == 1:
                matched_amenity = possible_matches[0]

        # ---------------------------------
        # Requested amenity could not be
        # safely resolved.
        # ---------------------------------

        if matched_amenity is None:
            return None

        amenity_ids.append(
            matched_amenity.id
        )

    return list(set(amenity_ids))

def search_properties_with_ai(
    db: Session,
    query: str,
    page: int = 1,
    page_size: int = 12,
):
    """
    Search real StayLeb properties using filters extracted
    from the user's natural-language query.

    Gemini interprets the query only.
    The existing property search service selects the properties.
    """

    # ---------------------------------
    # 1. Extract structured filters
    # ---------------------------------

    filters = extract_property_search_filters(
        query=query,
    )

    # ---------------------------------
    # 2. Resolve requested amenities
    # ---------------------------------

    amenity_ids = resolve_ai_amenity_ids(
        db=db,
        amenity_names=filters.amenities,
    )

    # ---------------------------------
    # 3. Unknown requested amenity
    #
    # Do not weaken the user's search by
    # silently ignoring the requirement.
    # ---------------------------------

    if amenity_ids is None:
        return {
            "items": [],
            "total": 0,
            "page": page,
            "page_size": page_size,
            "total_pages": 0,
        }

    # ---------------------------------
    # 4. Search REAL StayLeb properties
    # ---------------------------------

    return search_properties(
        db=db,
        location=filters.location,
        guests=filters.guests,
        min_price=filters.min_price,
        max_price=filters.max_price,
        property_type=filters.property_type,
        bedrooms=filters.bedrooms,
        bathrooms=filters.bathrooms,
        beds=filters.beds,
        amenity_ids=amenity_ids,
        sort="recommended",
        page=page,
        page_size=page_size,
    )