"use client";
import {createContext,useContext,useState,useSyncExternalStore,type ReactNode,type SelectHTMLAttributes} from 'react';
import Link from 'next/link';
import {coastalStays} from '@/lib/mock-data/listings';
import {properties} from '@/lib/mock-data/properties';
import type {Property} from '@/lib/types';
import {Icon} from '@/components/ui/Icon';
import {LocalImage} from '@/components/ui/LocalImage';
import {useSearchState} from '@/components/ui/Interactions';
type Filters={maxPrice:number;guests:number;amenities:string[];sort:string};
const defaults:Filters={maxPrice:500,guests:1,amenities:[],sort:'recommended'};
const ListingContext=createContext({filters:defaults,update:(_patch:Partial<Filters>)=>{}});
export function ListingProvider({children}:{children:ReactNode}){const [filters,setFilters]=useState(defaults);return <ListingContext.Provider value={{filters,update:patch=>setFilters(value=>({...value,...patch}))}}>{children}</ListingContext.Provider>;}
const subscribe=(callback:()=>void)=>{window.addEventListener('stayleb-favorites',callback);window.addEventListener('storage',callback);return()=>{window.removeEventListener('stayleb-favorites',callback);window.removeEventListener('storage',callback);};};
const readFavorites=()=>localStorage.getItem('stayleb-saved-property-ids') || '["batroun-sunset","cedar-peak","azure-horizon"]';
const serverFavorites=()=>'["batroun-sunset","cedar-peak","azure-horizon"]';
export function FavoriteButton({id}:{id:string}){const saved=JSON.parse(useSyncExternalStore(subscribe,readFavorites,serverFavorites)) as string[];const active=saved.includes(id);return <button type="button" aria-label={active?'Remove from favorites':'Save to favorites'} aria-pressed={active} className="w-8 h-8 rounded-full bg-white/95 grid place-items-center shadow-sm text-white" onClick={()=>{localStorage.setItem('stayleb-saved-property-ids',JSON.stringify(active?saved.filter(value=>value!==id):[...saved,id]));window.dispatchEvent(new Event('stayleb-favorites'));}}><Icon name="favorite" className={active?'text-rose-500':'text-slate-500'}/></button>;}
export function PropertyCard({property}:{property:Property}){return <article className="rounded-xl bg-white shadow-sm border border-slate-100 overflow-hidden group"><div className="aspect-[16/10] relative overflow-hidden"><Link href={`/properties/${property.id}`}><LocalImage src={property.image} alt={property.name} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"/></Link><span className="absolute top-3 left-3 rounded-full bg-white/95 px-2 py-1 text-[10px] font-semibold text-primary">ϟ Instant Book</span><div className="absolute top-3 right-3"><FavoriteButton id={property.id}/></div></div><div className="p-4"><div className="flex justify-between gap-1 text-[10px] text-slate-500"><span>{property.location}</span><strong className="text-primary">★ {property.rating}</strong></div><Link href={`/properties/${property.id}`} className="block text-base font-semibold mt-2 hover:text-white">{property.name}</Link><p className="text-xs text-slate-500 mt-1">{property.guests} guests · {property.bedrooms} beds · {property.amenities[2]}</p><div className="flex flex-wrap gap-1 mt-3">{property.amenities.slice(0,2).map(amenity=><span key={amenity} className="text-[10px] bg-surface-container-low rounded px-2 py-1 text-white">{amenity}</span>)}</div><div className="flex items-end justify-between border-t border-slate-100 pt-3 mt-3"><span><strong className="text-lg text-primary">${property.nightlyRate}</strong><span className="text-xs text-slate-500"> / night</span></span><span className="text-[10px] text-slate-500">${property.nightlyRate*3} total · 3 nts</span></div></div></article>;}
export function SearchFilters(){const {filters,update}=useContext(ListingContext);const {setQuery}=useSearchState();return <aside className="w-full lg:w-64 shrink-0 panel h-fit"><div className="flex items-center justify-between"><h2 className="font-semibold">Refine Filters</h2><button className="text-xs text-white" onClick={()=>{update(defaults);setQuery('');}}>Clear all</button></div><fieldset className="mt-6"><legend className="text-xs font-semibold uppercase tracking-wider">Price per night</legend><input aria-label="Maximum nightly price" type="range" min={100} max={600} step={25} value={filters.maxPrice} onChange={e=>update({maxPrice:Number(e.target.value)})} className="w-full accent-teal-700 mt-4"/><div className="flex justify-between text-xs"><span>$100</span><strong>Up to ${filters.maxPrice}</strong></div></fieldset><div className="flex justify-between items-center mt-6"><span className="text-sm font-medium">Guests</span><div className="flex items-center gap-3"><button aria-label="Fewer guests" className="secondary-button !p-2 !min-h-8" onClick={()=>update({guests:Math.max(1,filters.guests-1)})}>−</button><span>{filters.guests}</span><button aria-label="More guests" className="secondary-button !p-2 !min-h-8" onClick={()=>update({guests:Math.min(10,filters.guests+1)})}>+</button></div></div><fieldset className="mt-6 space-y-3"><legend className="text-xs font-semibold uppercase tracking-wider mb-4">Amenities</legend>{[['pool','Private Pool'],['sea','Sea View / Seafront'],['solar','24/7 Solar Power'],['wi-fi','High-Speed Wi-Fi'],['stone','Stone Architecture']].map(([value,label])=><label key={value} className="flex items-center gap-3 text-sm"><input type="checkbox" checked={filters.amenities.includes(value)} onChange={e=>update({amenities:e.target.checked?[...filters.amenities,value]:filters.amenities.filter(item=>item!==value)})} className="w-4 h-4 accent-teal-700"/>{label}</label>)}</fieldset><button className="primary-button w-full mt-6" onClick={()=>document.getElementById('listing-results')?.scrollIntoView({behavior:'smooth',block:'start'})}>View matching stays</button><button className="w-full text-xs mt-3 text-slate-500" onClick={()=>{update(defaults);setQuery('');}}>Reset to Defaults</button></aside>;}
export function SortSelect(props:SelectHTMLAttributes<HTMLSelectElement>){const {filters,update}=useContext(ListingContext);return <select {...props} value={filters.sort} onChange={e=>update({sort:e.target.value})}><option value="recommended">Recommended</option><option value="price-low">Price: Low to High</option><option value="price-high">Price: High to Low</option><option value="rating">Highest Rated</option></select>;}
export function SearchResultsGrid(){const {filters,update}=useContext(ListingContext);const {query,setQuery}=useSearchState();let visible=coastalStays.filter(property=>{const text=[property.name,property.location,...property.amenities].join(' ').toLowerCase();return property.nightlyRate<=filters.maxPrice&&property.guests>=filters.guests&&text.includes(query.toLowerCase())&&filters.amenities.every(amenity=>text.includes(amenity));});if(filters.sort==='price-low')visible=visible.toSorted((a,b)=>a.nightlyRate-b.nightlyRate);if(filters.sort==='price-high')visible=visible.toSorted((a,b)=>b.nightlyRate-a.nightlyRate);if(filters.sort==='rating')visible=visible.toSorted((a,b)=>b.rating-a.rating);return <div id="listing-results"><p role="status" className="text-xs text-slate-500 mb-4">{visible.length} matching {visible.length===1?'stay':'stays'}</p><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">{visible.map(property=><PropertyCard key={property.id} property={property}/>)}</div>{!visible.length&&<div className="panel py-14 text-center"><Icon name="search_off" className="text-4xl text-slate-400"/><h2 className="font-semibold text-xl mt-4">No stays match these filters</h2><p className="text-slate-500 my-4">Try a broader location, price range, or fewer amenities.</p><button className="primary-button" onClick={()=>{update(defaults);setQuery('');}}>Clear All Filters</button></div>}</div>;}
export function FavoritesGrid(){const ids=JSON.parse(useSyncExternalStore(subscribe,readFavorites,serverFavorites)) as string[];const records=[...coastalStays,...properties.filter(property=>!coastalStays.some(item=>item.id===property.id))].filter(property=>ids.includes(property.id));return <div>{records.length?<div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-6">{records.map(property=><PropertyCard property={property} key={property.id}/>)}</div>:<div className="panel text-center py-16"><Icon name="favorite_border" className="text-4xl text-primary"/><h2 className="text-xl font-semibold mt-4">No saved stays yet</h2><p className="text-slate-500 mt-2 mb-5">Tap the heart on any property to save it here.</p><Link href="/search" className="primary-button">Discover Properties</Link></div>}</div>;}
